### ISSUE TITLE
notiOne GPS support

### ISSUE THREAD

**Issue by pejotigrek** [n4ts/ha-notione#2]
is it possible to add notiOne GPS same way as regular bluetooth-based dongles?

**Comment by n4ts** [comment]
In my opinion, my custom-component also supports notiOne GPS :)

**Comment by pejotigrek** [comment]
hm, it didn't showed up in my config :(
I've got the pre-sales beta version that I've got for testing months ago - if that changes something [I can see it at notione's web panel without any problem tho].

**Comment by n4ts** [comment]
@pejotigrek can you send me output from https://api.notinote.me/secured/internal/devicelist after login?

**Comment by pejotigrek** [comment]
sure, but all I got is this:

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Feb 23 09:39:08 CET 2021
There was an unexpected error (type=Forbidden, status=403).
Access Denied
```

**Comment by n4ts** [comment]
@pejotigrek  You need to open the developer tools (CTRL + SHIFT + I in Chrome) in your browser (before logging in), then log in and find the request with name devicelist (this can be filtered by XHR requests). A need all output (JSON format).

**Comment by pejotigrek** [comment]
done, file below:
[response.txt](https://github.com/n4ts/ha-notione/files/6028762/response.txt)

**Comment by n4ts** [comment]
add in [bc0357b](https://github.com/n4ts/ha-notione/commit/bc0357b08f02bff393a96dc12ea8e7979e550ffa)
